services:
  - type: web
    name: tommax-portfolio
    env: node
    plan: free
    branch: main
    buildCommand: cd portfolio && npm ci && npm run build
    startCommand: cd portfolio && npm run start
    autoDeploy: true
